"""create database

Revision ID: ed1b1db28773
Revises: 
Create Date: 2023-06-02 20:02:39.852122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed1b1db28773"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("state_name", sa.String(), nullable=True),
        sa.Column("zip", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_location_id"), "location", ["id"], unique=False)
    op.create_index(op.f("ix_location_zip"), "location", ["zip"], unique=False)
    op.create_table(
        "car",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_number", sa.String(), nullable=False, unique=True),
        sa.Column("location_current_id", sa.Integer(), nullable=True),
        sa.Column("carrying", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_current_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_car_id"), "car", ["id"], unique=False)
    op.create_table(
        "cargo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_pick_up_id", sa.Integer(), nullable=True),
        sa.Column("location_delivery_id", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_delivery_id"],
            ["location.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_pick_up_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cargo_id"), "cargo", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cargo_id"), table_name="cargo")
    op.drop_table("cargo")
    op.drop_index(op.f("ix_car_id"), table_name="car")
    op.drop_table("car")
    op.drop_index(op.f("ix_location_zip"), table_name="location")
    op.drop_index(op.f("ix_location_id"), table_name="location")
    op.drop_table("location")
    # ### end Alembic commands ###
